env:
    token: "ENCRYPTED[18gkq4oge92qq4h30qpe3i0h9r6djm0427acqf7]"

task:
  name: "Chime AOSPA"
  timeout_in: 1h
  container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G

  Build_script:
      - bash cosmiclang.sh